### ISSUE TITLE
Paper URL to DOI

### ISSUE THREAD

**Issue by rgieseke** [rgieseke/cite#4]
An option to go from (potentially changing) article URL to its DOI coud be useful.

**Comment by penrudee** [comment]
I try to use cite in my website How to implement it .

**Comment by rgieseke** [comment]
What exactly are you trying to do? It's mainly thought as being used on the command line atm.

**Comment by penrudee** [comment]
> What exactly are you trying to do? It's mainly thought as being used on the command line atm.

I try to implement it in the website under the textrea but if you said  only for command line that's ok . May be i fine the way out.Thank you.

**Comment by penrudee** [comment]
The Cite is very usuful if it can be apply in a normal website like [.Do](https://www.citethisforme.com/citation-generator) you have a solution about it?

**Comment by rgieseke** [comment]
Cite is a commanline tool primarily, but the service it uses  is a web-based API you could use in another website (i think):

https://citation.crosscite.org/

https://citation.crosscite.org/docs.html

**Comment by penrudee** [comment]
> Cite is a commanline tool primarily, but the service it uses is a web-based API you could use in another website (i think):
> 
> https://citation.crosscite.org/
> 
> https://citation.crosscite.org/docs.html

Thank you very much.🙏

**Comment by rgieseke** [comment]
The original question could probably be achieved by some command line json output wrangling. 

> An option to go from (potentially changing) article URL to its DOI coud be useful.
